Algoritmo "Meu Primeiro algoritimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Paulo Quirino
// Data atual  : 10/01/2022
Var
// Seção de Declarações das variáveis 
   nota: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva("Resultado: ", nota)

Fimalgoritmo