Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Paulo Quirino
// Data atual  : 10/01/2022
Var
// Seção de Declarações das variáveis 
   primieroNome, segundoNome, cidade, endereco: caractere,
   idade: inteiro,

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   

Fimalgoritmo